version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    networks:
            - jupiter

networks: 
    jupiter:
        driver: bridge